name: C Build with Android NDK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.5
    - name: Set up NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip
        echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r21e" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/android-ndk-r21e" >> $GITHUB_PATH
    - name: Compile C program with NDK
      run: |
        $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk APP_ABI=armeabi-v7a APP_PLATFORM=android-16
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-executable
        path: libs/armeabi-v7a/hello
