name: Build Minimal FFmpeg for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential autoconf automake libtool git pkg-config make curl unzip zlib1g-dev yasm \
                                 libc6:i386 libncurses5:i386 libstdc++6:i386 lib32z1 lib32bz2-1.0

      - name: Download NDK
        run: |
          mkdir ndk && cd ndk
          curl -LO https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/ndk/android-ndk-r25c" >> $GITHUB_ENV

      - name: Download FFmpeg source
        run: |
          curl -LO https://ffmpeg.org/releases/ffmpeg-6.1.1.tar.xz  # 使用最新的 FFmpeg 6.1.1 版本
          tar -xf ffmpeg-6.1.1.tar.xz
          cd ffmpeg-6.1.1

      - name: Configure FFmpeg (minimal)
        run: |
          cd ffmpeg-6.1.1
          ./configure \
            --target-os=android \
            --arch=arm \
            --enable-cross-compile \
            --cross-prefix="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-" \
            --sysroot="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/sysroot" \
            --cc="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-clang" \
            --cxx="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-clang++" \
            --prefix="$GITHUB_WORKSPACE/build" \
            --disable-everything \
            --enable-decoder=mpeg4 \
            --enable-shared \
            --disable-asm  # 禁用汇编优化

      - name: Build FFmpeg
        run: make -j $(nproc)

      - name: Install FFmpeg
        run: make install

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-build-minimal
          path: build/