name: Build FFmpeg for Android (Matching build.sh config)

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Download NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip android-ndk-r26d-linux.zip
          echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r26d" >> $GITHUB_ENV
          echo "$GITHUB_WORKSPACE/android-ndk-r26d" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential autoconf automake libtool git pkg-config make curl unzip zlib1g-dev

      - name: Download FFmpeg source
        run: |
          curl -LO https://www.ffmpeg.org/releases/ffmpeg-6.1.1.tar.xz
          tar -xf ffmpeg-6.1.1.tar.xz
          cd ffmpeg-6.1.1

      - name: Set compiler environment variables
        run: |
          echo "CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang" >> $GITHUB_ENV
          echo "CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24-clang++" >> $GITHUB_ENV
          echo "NM=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm" >> $GITHUB_ENV
          echo "STRIP=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip" >> $GITHUB_ENV
          echo "PKG_CONFIG=pkg-config" >> $GITHUB_ENV

      - name: Configure FFmpeg 
        run: |
          cd ffmpeg-6.1.1
          ./configure \
            --arch=armeabi-v7a \
            --as="$CC" \
            --cc="$CC" \
            --cxx="$CXX" \
            --nm="$NM" \
            --pkg-config="$PKG_CONFIG" \
            --strip="$STRIP" \
            --cross-prefix="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-" \
            --sysroot="${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/sysroot" \
            --disable-indevs \
            --disable-outdevs \
            --enable-indev=lavfi \
            --disable-static \
            --disable-symver \
            --enable-cross-compile \
            --enable-gnutls \
            --enable-gpl \
            --enable-version3 \
            --enable-jni \
            --enable-lcms2 \
            --enable-libaom \
            --enable-libass \
            --enable-libbluray \
            --enable-libdav1d \
            --enable-libfreetype \
            --enable-libgme \
            --enable-libmp3lame \
            --enable-libopencore-amrnb \
            --enable-libopencore-amrwb \
            --enable-libopenmpt \
            --enable-libopus \
            --enable-librav1e \
            --enable-libsoxr \
            --enable-libsrt \
            --enable-libssh \
            --enable-libsvtav1 \
            --enable-libtheora \
            --enable-libv4l2  \
            --enable-libvidstab \
            --enable-libvo-amrwbenc \
            --enable-libvorbis \
            --enable-libvpx \
            --enable-libwebp \
            --enable-libx264 \
            --enable-libx265 \
            --enable-libxml2 \
            --enable-libxvid \
            --enable-libzimg \
            --enable-mediacodec \
            --enable-opencl \
            --enable-shared \
            --prefix="$GITHUB_WORKSPACE/build" \
            --target-os=android \
            --extra-libs="-landroid-glob" \
            --disable-vulkan \
            --enable-neon \
            --disable-libfdk-aac 

      - name: Build FFmpeg
        run: make -j $(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-build-armeabi-v7a
          path: build/