name: Build FFmpeg for Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TERMUX_ARCH: arm
      TERMUX_PREFIX: /data/data/com.termux/files/usr
      TERMUX_PKG_BUILDDIR: ${{ github.workspace }}/build
      TERMUX_PKG_SRCDIR: ${{ github.workspace }}/src
      TERMUX_PKG_MASSAGEDIR: ${{ github.workspace }}/massage
      ANDROID_NDK_HOME: ${{ github.workspace }}/android-ndk-r21e
      AS: ${{ github.workspace }}/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-as
      CC: ${{ github.workspace }}/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang
      CXX: ${{ github.workspace }}/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang++
      NM: ${{ github.workspace }}/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm
      PKG_CONFIG: pkg-config
      STRIP: ${{ github.workspace }}/android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip
      TERMUX_HOST_PLATFORM: arm-linux-androideabi

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.5

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          build-essential \
          cmake \
          git \
          libtool \
          pkg-config \
          wget \
          yasm \
          zlib1g-dev

    - name: Download Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip

    - name: Download FFmpeg source
      run: |
        mkdir -p $TERMUX_PKG_SRCDIR
        wget https://www.ffmpeg.org/releases/ffmpeg-6.1.1.tar.xz -O $TERMUX_PKG_SRCDIR/ffmpeg-6.1.1.tar.xz
        tar -xf $TERMUX_PKG_SRCDIR/ffmpeg-6.1.1.tar.xz -C $TERMUX_PKG_SRCDIR
        mv $TERMUX_PKG_SRCDIR/ffmpeg-6.1.1/* $TERMUX_PKG_SRCDIR

    - name: Create build directory
      run: mkdir -p $TERMUX_PKG_BUILDDIR

    - name: Configure and build FFmpeg
      run: |
        cd $TERMUX_PKG_BUILDDIR

        _EXTRA_CONFIGURE_FLAGS=""
        if [ $TERMUX_ARCH = "arm" ]; then
          _ARCH="armeabi-v7a"
          _EXTRA_CONFIGURE_FLAGS="--enable-neon"
        elif [ $TERMUX_ARCH = "i686" ]; then
          _ARCH="x86"
          _EXTRA_CONFIGURE_FLAGS="--disable-asm"
        elif [ $TERMUX_ARCH = "x86_64" ]; then
          _ARCH="x86_64"
        elif [ $TERMUX_ARCH = "aarch64" ]; then
          _ARCH=$TERMUX_ARCH
          _EXTRA_CONFIGURE_FLAGS="--enable-neon"
        else
          echo "Unsupported arch: $TERMUX_ARCH"
          exit 1
        fi

        $TERMUX_PKG_SRCDIR/configure \
          --arch="${_ARCH}" \
          --as="$AS" \
          --cc="$CC" \
          --cxx="$CXX" \
          --nm="$NM" \
          --pkg-config="$PKG_CONFIG" \
          --strip="$STRIP" \
          --cross-prefix="${TERMUX_HOST_PLATFORM}-" \
          --disable-indevs \
          --disable-outdevs \
          --disable-static \
          --disable-symver \
          --enable-cross-compile \
          --enable-gpl \
          --enable-version3 \
          --enable-shared \
          --prefix="$TERMUX_PREFIX" \
          --target-os=android \
          --extra-libs="-landroid-glob" \
          $_EXTRA_CONFIGURE_FLAGS

        make -j$(nproc)

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ffmpeg-build
        path: $TERMUX_PKG_BUILDDIR