name: Build FFmpeg for Termux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_NDK_VERSION: r21e
      ANDROID_API_LEVEL: 21
      TARGET_ARCH: armeabi-v7a

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'

    - name: Download and extract Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux-x86_64.zip
        unzip android-ndk-${{ env.ANDROID_NDK_VERSION }}-linux-x86_64.zip
        mv android-ndk-${{ env.ANDROID_NDK_VERSION }} $HOME/android-ndk

    - name: Set up environment variables
      run: |
        echo "export ANDROID_NDK_HOME=$HOME/android-ndk" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config git yasm

    - name: Clone FFmpeg repository
      run: |
        git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
        cd ffmpeg
        git checkout release/4.4

    - name: Configure and build FFmpeg
      run: |
        cd ffmpeg
        ./configure \
          --prefix=$HOME/ffmpeg_build \
          --target-os=android \
          --arch=${{ env.TARGET_ARCH }} \
          --cpu=armv7-a \
          --cross-prefix=arm-linux-androideabi- \
          --sysroot=$ANDROID_NDK_HOME/platforms/android-${{ env.ANDROID_API_LEVEL }}/arch-arm \
          --extra-cflags="-I$ANDROID_NDK_HOME/sysroot/usr/include/arm-linux-androideabi -I$ANDROID_NDK_HOME/sysroot/usr/include" \
          --extra-ldflags="-L$ANDROID_NDK_HOME/platforms/android-${{ env.ANDROID_API_LEVEL }}/arch-arm/usr/lib" \
          --enable-cross-compile \
          --disable-static \
          --enable-shared \
          --disable-doc \
          --disable-programs \
          --disable-everything \
          --enable-avcodec \
          --enable-avformat \
          --enable-swscale \
          --enable-avfilter \
          --enable-network \
          --enable-protocols \
          --enable-demuxers \
          --enable-muxers \
          --enable-decoders \
          --enable-encoders \
          --enable-parsers \
          --enable-filters
        make -j$(nproc)
        make install

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg-build
        path: $HOME/ffmpeg_build