name: Download YouTube Video

on: [push]

jobs:
  download_video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: List all available streams
        env:
          COOKIES_CONTENT: ${{ secrets.COOKIES }}
        run: |
          yt-dlp --cookies <(echo "$COOKIES_CONTENT") -F \
          https://youtu.be/vHFtta8t_jA?si=M4UhieTJFRptLU0X

      - name: Setup FFmpeg
        run: |
          chmod +x ffmpeg
          echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH

      - name: Download video and audio-A
        env:
          COOKIES_CONTENT: ${{ secrets.COOKIES }}
          INCLUDE_SECTIONS: "false"
          ENABLE_MULTITHREAD: "true"
        run: |
          好yt-dlp --cookies <(echo "$COOKIES_CONTENT") -f 313 \
          $([[ "$INCLUDE_SECTIONS" == "true" ]] && echo --download-sections *5-2:36) \
          $([[ "$ENABLE_MULTITHREAD" == "true" ]] && echo --concurrent-fragments 10) \
          -o "AAA.webm" \
          https://youtu.be/vHFtta8t_jA?si=M4UhieTJFRptLU0X

      - name: Download video and audio-B
        env:
          COOKIES_CONTENT: ${{ secrets.COOKIES }}
          INCLUDE_SECTIONS: "false"
          ENABLE_MULTITHREAD: "true"
        run: |
          yt-dlp --cookies <(echo "$COOKIES_CONTENT") -f 313 \
          $([[ "$INCLUDE_SECTIONS" == "true" ]] && echo --download-sections *5-2:36) \
          $([[ "$ENABLE_MULTITHREAD" == "true" ]] && echo --concurrent-fragments 10) \
          -o "BBB.webm" \
          https://youtu.be/dHfrWznQWgw?si=dG_cP4tLR44OCYBK
      
      - name: Test x264 encoding
        run: |
          ffmpeg -i AAA.webm -i BBB.webm \
          -filter_complex "[0:v]scale=-2:1920,eq=brightness=-0.04,split=2[original][copy]; \
          [copy]format=yuva444p,geq=lum='p(X,Y)':a='if(between(X,780,1080)*between(Y,1800,1920),255,0)',boxblur=10:2[mask]; \
          [original][mask]overlay,split=3[seg1][seg2][seg3]; \
          [seg1]trim=115:190,setpts=PTS-STARTPTS[seg1out]; \
          [seg2]trim=41:113,setpts=PTS-STARTPTS[seg2out]; \
          [seg3]trim=197:215,setpts=PTS-STARTPTS[seg3out]; \
          [seg1out][seg2out][seg3out]concat=n=3:v=1:a=0[outv]; \
          [1:v]transpose=1,scale=-2:1920,eq=brightness=-0.05,split=3[seg1][seg2][seg3]; \
          [seg1]trim=115:190,setpts=PTS-STARTPTS[seg1out]; \
          [seg2]trim=41:113,setpts=PTS-STARTPTS[seg2out]; \
          [seg3]trim=197:215,setpts=PTS-STARTPTS[seg3out]; \
          [seg1out][seg2out][seg3out]concat=n=3:v=1:a=0[outv1]; \
          [outv][outv1]concat=n=2:v=1:a=0[outv3]" \
          -map "[outv3]" -c:v libx264 -preset slower -crf 15 test_video.mp4

      - name: Upload encoded video
        uses: actions/upload-artifact@v4
        with:
          name: encoded-video
          path: test_video.mp4
