name: Download YouTube Video

on: [push]

jobs:
  download_video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: List all available streams
        env:
          COOKIES_CONTENT: ${{ secrets.COOKIES }}
        run: |
          yt-dlp --cookies <(echo "$COOKIES_CONTENT") -F \
          https://youtu.be/6B93A9RsI7Y?si=S5zCNCBWaTKnh8JM

      - name: Make FFmpeg executable
        run: chmod +x ffmpeg

      - name: Set FFMPEG_PATH
        run: echo "$GITHUB_WORKSPACE" >> $GITHUB_PATH

      - name: Download video and audio
        run: |
          yt-dlp --cookies cookies.txt -f 313 \
          $([[ "$INCLUDE_SECTIONS" == "true" ]] && echo --download-sections *5-2:36) \
          $([[ "$ENABLE_MULTITHREAD" == "true" ]] && echo --concurrent-fragments 10) \
          -o "downloads/AAA.webm" \
          https://youtu.be/6B93A9RsI7Y?si=S5zCNCBWaTKnh8JM
        env:
          INCLUDE_SECTIONS: "false"
          ENABLE_MULTITHREAD: "true"

      - name: Test x264 encoding
        run: |
          input_file="downloads/AAA.webm"
          output_file="encoded_output/test_video.mp4"
          mkdir -p encoded_output
          ffmpeg -i "$input_file" -ss 00:00:00 -t 5 -vf "scale=1920:1080,fps=29.97" -c:v libx264 "$output_file"
          echo "Encoding completed: $output_file"

      - name: Upload encoded video
        uses: actions/upload-artifact@v4
        with:
          name: encoded-video
          path: encoded_output/test_video.mp4
