name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: loading-animation
          # 添加 --debug 参数，强制 wrangler 输出调试日志
          wranglerFlags: "--debug"

      # 如果 wrangler 失败，我们可以打印日志文件
      - name: Show Wrangler Logs
        run: |
          if [ -f "/home/runner/.config/.wrangler/logs/*.log" ]; then
            cat /home/runner/.config/.wrangler/logs/*.log
          else
            echo "No wrangler logs found."
          fi
