name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: loading-animation
          # 使用 `command` 指定带 --debug 的 wrangler deploy
          command: deploy --debug

      # 打印日志文件
      - name: Show Wrangler Logs
        run: |
          LOG_DIR="/home/runner/.config/.wrangler/logs"
          if [ -d "$LOG_DIR" ]; then
            echo "Printing Wrangler logs..."
            cat "$LOG_DIR"/*.log
          else
            echo "No Wrangler logs found."
          fi
