name: Download YouTube Video

on:
  push:
    branches: [main]

jobs:
  download_video:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yt-dlp
        run: pip install yt-dlp
      - name: Download video
        run: yt-dlp --cookies cookies.txt -F -f bestvideo --output "downloads/%(title)s.%(ext)s" https://youtu.be/R6tDoo0hSOs?si=rwSyyr1WRLBDhBNJ
      - name: Upload downloaded videos
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-videos
          path: downloads/**
