name: Nmap Scan on Push

on:
  push:
    branches: [main]  # 指定分支，可以修改为你的主分支

jobs:
  nmap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install nmap
        run: sudo apt-get update && sudo apt-get install nmap
      - name: Run nmap scan
        run: nmap -Pn -p 45678 144.202.105.221
