name: Build for armv7l

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download source code
      run: |
        wget https://github.com/peanut996/CloudflareWarpSpeedTest/archive/refs/tags/v1.5.3.tar.gz
        tar -xzf v1.5.3.tar.gz
        mv CloudflareWarpSpeedTest-1.5.3/* .

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        go mod download

    - name: Build for armv7l
      run: |
        GOARCH=arm GOARM=7 go build -o CloudflareWarpSpeedTest-armv7l

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: CloudflareWarpSpeedTest-armv7l
        path: CloudflareWarpSpeedTest-armv7l
