name: Build for armv7l

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download source code
      run: |
        wget https://github.com/peanut996/CloudflareWarpSpeedTest/archive/refs/tags/v1.5.3.tar.gz
        tar -xzf v1.5.3.tar.gz
        mv CloudflareWarpSpeedTest-1.5.3/* .
    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: |
        go mod download
    - name: Build for armv7l
      run: |
        GOARCH=arm GOARM=7 go build -o CloudflareWarpSpeedTest-armv7l
    - name: Create release artifact
      uses: softprops/action-gh-release@v1
      with:
        files: CloudflareWarpSpeedTest-armv7l
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
