name: Build FFmpeg with x264

on: [push]

jobs:
  build_ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cmake \
            git \
            libass-dev \
            libfdk-aac-dev \
            libmp3lame-dev \
            libopus-dev \
            libtheora-dev \
            libtool \
            libvorbis-dev \
            pkg-config \
            texinfo \
            wget \
            yasm \
            zlib1g-dev \
            nasm
      - name: Check for existing FFmpeg installation
        run: |
          if command -v ffmpeg &> /dev/null; then
              echo "FFmpeg is already installed. Version:"
              ffmpeg -version
              exit 0
          else
              echo "FFmpeg not found. Proceeding with installation."
          fi
      - name: Clone x264
        run: |
          git clone --depth 1 https://code.videolan.org/videolan/x264.git
          cd x264
          ./configure --enable-shared
          make -j$(nproc)
          sudo make install
          cd ..
      - name: Download and extract FFmpeg
        run: |
          wget https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
          tar -xjf ffmpeg-snapshot.tar.bz2
          mv ffmpeg ffmpeg-source
      - name: Build FFmpeg
        run: |
          cd ffmpeg-source
          ./configure --enable-gpl --enable-libx264 --enable-nonfree --enable-static --disable-shared --prefix=/usr/local/ff2024
          make -j$(nproc)
          sudo make install
          sudo ldconfig
      - name: Verify FFmpeg installation
        run: |
          /usr/local/ff2024/bin/ffmpeg -version
          ls /usr/local/ff2024/bin

      - name: Upload FFmpeg as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg
          path: /usr/local/ff2024/bin/ffmpeg
