name: Build FFmpeg with x264

on: [push]

jobs:
  build_ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            autoconf \
            automake \
            build-essential \
            cmake \
            git \
            libass-dev \
            libfdk-aac-dev \
            libmp3lame-dev \
            libopus-dev \
            libtheora-dev \
            libtool \
            libvorbis-dev \
            pkg-config \
            texinfo \
            wget \
            yasm \
            zlib1g-dev \
            nasm
      - name: Clone x264
        run: |
          git clone --depth 1 https://code.videolan.org/videolan/x264.git
          cd x264
          ./configure --enable-shared --enable-static  # Enable static library
          make -j$(nproc)
          sudo make install
          cd ..
      - name: Remove existing FFmpeg directory if it exists
        run: |
          if [ -d "ffmpeg" ]; then
            rm -rf ffmpeg
          fi
      - name: Clone FFmpeg
        run: |
          git clone --depth 1 https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          ./configure --enable-gpl --enable-libx264 --enable-nonfree --enable-static --disable-shared --prefix=/usr/local/ff2024  # Specify installation directory
          make -j$(nproc)
          sudo make install
          sudo ldconfig  # 更新共享库缓存
          cd ..
      - name: Verify FFmpeg installation
        run: |
          /usr/local/ff2024/bin/ffmpeg -version  # Check ffmpeg version
          ls /usr/local/ff2024/bin  # List all files in the installation directory

      - name: Upload FFmpeg as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg
          path: /usr/local/ff2024/bin/ffmpeg  # Upload the ffmpeg executable
