name: Download YouTube Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Enter YouTube video URL'
        required: true
        default: 'https://youtu.be/6B93A9RsI7Y?si=S5zCNCBWaTKnh8JM'
      enable_sections:
        description: 'Enable video section trimming?'
        required: true
        type: choice
        options: 
          - 'false'
          - 'true'
        default: 'false'
      enable_multithread:
        description: 'Enable multi-threaded download?'
        required: true
        type: choice
        options: 
          - 'false'
          - 'true'
        default: 'false'
      start_time:
        description: 'Start time (if section trimming is enabled, format: 00:00:00)'
        required: false
        default: '00:00:00'
      end_time:
        description: 'End time (if section trimming is enabled, format: 00:02:00)'
        required: false
        default: '00:02:00'

jobs:
  download_video:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yt-dlp
        run: pip install yt-dlp

      - name: List all available streams
        run: |
          yt-dlp --cookies cookies.txt -F ${{ github.event.inputs.video_url }}

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download video and audio
        run: |
          # 初始化命令
          CMD="yt-dlp --cookies cookies.txt -f bestvideo[ext=webm]"
          
          # 根据输入添加截取时间段参数
          if [ "${{ github.event.inputs.enable_sections }}" == "true" ]; then
            CMD="$CMD --download-sections *${{ github.event.inputs.start_time }}-${{ github.event.inputs.end_time }}"
          fi
          
          # 根据输入添加多线程下载参数
          if [ "${{ github.event.inputs.enable_multithread }}" == "true" ]; then
            CMD="$CMD --concurrent-fragments 10"
          fi
          
          # 添加输出路径和视频链接
          CMD="$CMD -o \"downloads/%(title)s.%(ext)s\" ${{ github.event.inputs.video_url }}"
          
          # 输出并执行命令
          echo "Running command: $CMD"
          eval $CMD
        shell: bash

      - name: Upload downloaded videos
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-videos
          path: downloads/**
